version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/Dockerfile
    image: laravel-app
    container_name: api-send-mail
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: postgres
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_DATABASE: send-mail
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres2024
    volumes:
      - ./infra/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
