version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: laravel
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
