version: "3.8"
services:
    # PHP Service
    php:
      container_name: api-send-mail
      build:
        context: .
        dockerfile: ./infra/docker/Dockerfile
        args:
          - APP_ENV=${APP_ENV}
      environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      ports:
        - '${APP_PORT:-8000}:80'
      network_mode: bridge
